#!/usr/bin/env python3
"""
EMA / HEMA / HMA / KAMA / ZLEMA trend-probe tournament.

Research-only. Frozen/live Quality Flow remains unchanged.
"""
from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd

from research_notes.hema_research import fetch_symbol, regular_1h, resample_closed_4h, ema
from research_notes.hema_qf_portfolio import SYMBOLS, prepare_symbol

OUT = Path("trend_probe_tournament")
OUT.mkdir(exist_ok=True)

HORIZONS = [1, 2, 4, 6, 10, 20]
RANDOM_SEEDS = list(range(500))
WARMUP = 215
INDICATORS = ["EMA", "HEMA", "HMA", "KAMA", "ZLEMA"]
FEATURES = ["slope", "gap", "gap_delta", "price_dist_fast"]


def month_key(ts) -> str:
    t = pd.Timestamp(ts)
    if t.tzinfo is not None:
        t = t.tz_localize(None)
    return str(t.to_period("M"))


def wma(s: pd.Series, length: int) -> pd.Series:
    n = int(length)
    weights = np.arange(1, n + 1, dtype=float)
    denom = weights.sum()
    return s.rolling(n).apply(lambda x: float(np.dot(x, weights) / denom), raw=True)


def hma(s: pd.Series, length: int) -> pd.Series:
    n = int(length)
    half = max(1, n // 2)
    root = max(1, int(math.sqrt(n)))
    raw = 2.0 * wma(s, half) - wma(s, n)
    return wma(raw, root)


def kama(s: pd.Series, er_length: int, fast: int = 2, slow: int = 30) -> pd.Series:
    """Classic Kaufman adaptive MA with ER window = requested line length."""
    n = int(er_length)
    change = (s - s.shift(n)).abs()
    volatility = s.diff().abs().rolling(n).sum()
    er = (change / volatility.replace(0.0, np.nan)).fillna(0.0)
    fast_sc = 2.0 / (fast + 1.0)
    slow_sc = 2.0 / (slow + 1.0)
    sc = (er * (fast_sc - slow_sc) + slow_sc) ** 2

    out = pd.Series(np.nan, index=s.index, dtype=float)
    vals = s.to_numpy(dtype=float)
    scv = sc.to_numpy(dtype=float)
    first = None
    for i, v in enumerate(vals):
        if np.isfinite(v):
            first = i
            out.iloc[i] = v
            break
    if first is None:
        return out
    prev = float(out.iloc[first])
    for i in range(first + 1, len(s)):
        v = vals[i]
        if not np.isfinite(v):
            out.iloc[i] = prev
            continue
        a = scv[i] if np.isfinite(scv[i]) else slow_sc ** 2
        prev = prev + a * (v - prev)
        out.iloc[i] = prev
    return out


def zlema(s: pd.Series, length: int) -> pd.Series:
    n = int(length)
    lag = max(1, int((n - 1) // 2))
    adjusted = s + (s - s.shift(lag))
    return adjusted.ewm(span=n, adjust=False).mean()


def add_probes(df: pd.DataFrame) -> pd.DataFrame:
    x = df.copy()
    close = x["Close"].astype(float)

    # EMA control.
    x["EMA_fast"] = ema(close, 20)
    x["EMA_slow"] = ema(close, 40)

    # HEMA already generated by the research prep.
    x["HEMA_fast"] = x["HEMA20"].astype(float)
    x["HEMA_slow"] = x["HEMA40"].astype(float)

    x["HMA_fast"] = hma(close, 20)
    x["HMA_slow"] = hma(close, 40)

    x["KAMA_fast"] = kama(close, 20, 2, 30)
    x["KAMA_slow"] = kama(close, 40, 2, 30)

    x["ZLEMA_fast"] = zlema(close, 20)
    x["ZLEMA_slow"] = zlema(close, 40)

    for name in INDICATORS:
        f = x[f"{name}_fast"]
        s = x[f"{name}_slow"]
        x[f"{name}_bull"] = f > s
        x[f"{name}_cross_up"] = (f > s) & (f.shift(1) <= s.shift(1))
        px = close.replace(0.0, np.nan)
        gap = (f - s) / px * 100.0
        x[f"{name}_slope"] = f.diff() / px * 100.0
        x[f"{name}_gap"] = gap
        x[f"{name}_gap_delta"] = gap.diff()
        x[f"{name}_price_dist_fast"] = (close - f) / px * 100.0
    return x


def spy_return(spy: pd.DataFrame, entry_ts, exit_ts) -> float:
    if entry_ts not in spy.index or exit_ts not in spy.index:
        return np.nan
    e = float(spy.loc[entry_ts, "Open"])
    x = float(spy.loc[exit_ts, "Close"])
    if not np.isfinite(e) or not np.isfinite(x) or e <= 0:
        return np.nan
    return x / e - 1.0


def forward_record(sym: str, df: pd.DataFrame, spy: pd.DataFrame, i: int, kind: str) -> dict | None:
    if i + max(HORIZONS) >= len(df) or i + 1 >= len(df):
        return None
    entry_i = i + 1
    entry = float(df["Open"].iloc[entry_i])
    if not np.isfinite(entry) or entry <= 0:
        return None
    rec = {
        "symbol": sym,
        "kind": kind,
        "signal_time": str(df.index[i]),
        "entry_time": str(df.index[entry_i]),
        "entry": entry,
        "year": int(df.index[i].year),
        "month": month_key(df.index[i]),
    }
    for h in HORIZONS:
        xi = entry_i + h - 1
        px = float(df["Close"].iloc[xi])
        r = px / entry - 1.0
        sr = spy_return(spy, df.index[entry_i], df.index[xi])
        rec[f"ret_{h}"] = r
        rec[f"excess_{h}"] = r - sr if np.isfinite(sr) else np.nan
    return rec


def summarize_forward(d: pd.DataFrame) -> dict:
    out = {"n": int(len(d))}
    for h in HORIZONS:
        r = d[f"ret_{h}"].dropna().astype(float) if f"ret_{h}" in d else pd.Series(dtype=float)
        e = d[f"excess_{h}"].dropna().astype(float) if f"excess_{h}" in d else pd.Series(dtype=float)
        out[f"mean_ret_{h}_pct"] = float(r.mean() * 100.0) if len(r) else None
        out[f"median_ret_{h}_pct"] = float(r.median() * 100.0) if len(r) else None
        out[f"hit_{h}_pct"] = float((r > 0).mean() * 100.0) if len(r) else None
        out[f"mean_excess_{h}_pct"] = float(e.mean() * 100.0) if len(e) else None
    return out


def stable_rng(seed: int, key: str) -> np.random.Generator:
    b = hashlib.sha256(f"{seed}|{key}".encode()).digest()[:8]
    return np.random.default_rng(int.from_bytes(b, "little", signed=False))


def build_random_pool_for_indicator(
    frames: dict[str, pd.DataFrame],
    spy: pd.DataFrame,
    indicator: str,
) -> dict[tuple[str, str], np.ndarray]:
    """Precompute numeric random-control pools for speed; columns are ret/excess by horizon."""
    buckets: dict[tuple[str, str], list[list[float]]] = {}
    cross_col = f"{indicator}_cross_up"
    for sym, df in frames.items():
        for i in range(WARMUP, len(df)):
            if i + max(HORIZONS) >= len(df):
                continue
            if bool(df[cross_col].iloc[i]):
                continue
            rec = forward_record(sym, df, spy, i, "random")
            if rec is None:
                continue
            row = []
            for h in HORIZONS:
                row.extend([float(rec[f"ret_{h}"]), float(rec[f"excess_{h}"])])
            buckets.setdefault((sym, rec["month"]), []).append(row)
    return {k: np.asarray(v, dtype=float) for k, v in buckets.items()}


def random_compare(events: pd.DataFrame, frames: dict[str, pd.DataFrame], spy: pd.DataFrame, indicator: str) -> tuple[dict, pd.DataFrame]:
    counts = events.groupby(["symbol", "month"]).size()
    pools = build_random_pool_for_indicator(frames, spy, indicator)
    rows = []
    for seed in RANDOM_SEEDS:
        pieces = []
        for (sym, month), n in counts.items():
            pool = pools.get((sym, month))
            if pool is None or len(pool) == 0:
                continue
            rng = stable_rng(seed, f"{sym}|{month}")
            take = int(n)
            idx = rng.choice(len(pool), size=take, replace=(len(pool) < take))
            pieces.append(pool[np.atleast_1d(idx)])
        arr = np.concatenate(pieces, axis=0) if pieces else np.empty((0, 2 * len(HORIZONS)))
        s = {"n": int(len(arr)), "seed": seed}
        for j, h in enumerate(HORIZONS):
            rv = arr[:, 2*j] if len(arr) else np.array([], dtype=float)
            evv = arr[:, 2*j+1] if len(arr) else np.array([], dtype=float)
            rv = rv[np.isfinite(rv)]
            evv = evv[np.isfinite(evv)]
            s[f"mean_ret_{h}_pct"] = float(rv.mean() * 100.0) if len(rv) else None
            s[f"median_ret_{h}_pct"] = float(np.median(rv) * 100.0) if len(rv) else None
            s[f"hit_{h}_pct"] = float((rv > 0).mean() * 100.0) if len(rv) else None
            s[f"mean_excess_{h}_pct"] = float(evv.mean() * 100.0) if len(evv) else None
        rows.append(s)
        if seed % 100 == 0:
            print("RANDOM", indicator, seed)
    rdf = pd.DataFrame(rows)
    ev = summarize_forward(events)
    comp = {}
    for h in HORIZONS:
        col = f"mean_excess_{h}_pct"
        vals = rdf[col].dropna().astype(float)
        actual = ev.get(col)
        comp[str(h)] = {
            "actual_mean_excess_pct": actual,
            "random_mean_pct": float(vals.mean()) if len(vals) else None,
            "random_p2_5_pct": float(vals.quantile(0.025)) if len(vals) else None,
            "random_p50_pct": float(vals.quantile(0.5)) if len(vals) else None,
            "random_p97_5_pct": float(vals.quantile(0.975)) if len(vals) else None,
            "one_sided_p_random_ge_actual": float((1 + int((vals >= actual).sum())) / (len(vals) + 1)) if len(vals) and actual is not None else None,
        }
    return comp, rdf

def qf_record(sym: str, df: pd.DataFrame, spy: pd.DataFrame, i: int) -> dict | None:
    if i < 1 or i + 20 >= len(df) or i + 1 >= len(df):
        return None
    rec = forward_record(sym, df, spy, i, "qf")
    if rec is None:
        return None
    entry_i = i + 1
    entry = float(df["Open"].iloc[entry_i])
    w = df.iloc[entry_i:i + 11]
    rec["mae10_pct"] = (float(w["Low"].min()) / entry - 1.0) * 100.0
    rec["mfe10_pct"] = (float(w["High"].max()) / entry - 1.0) * 100.0
    rec["close_at_signal"] = float(df["Close"].iloc[i])
    for name in INDICATORS:
        rec[f"{name}_bull"] = bool(df[f"{name}_bull"].iloc[i])
        for feat in FEATURES:
            v = df[f"{name}_{feat}"].iloc[i]
            rec[f"{name}_{feat}"] = float(v) if np.isfinite(v) else np.nan
    return rec


def summarize_qf_group(g: pd.DataFrame) -> dict:
    if g.empty:
        return {"n": 0}
    out = {
        "n": int(len(g)),
        "mean_excess10_pct": float(g["excess_10"].mean() * 100.0),
        "median_excess10_pct": float(g["excess_10"].median() * 100.0),
        "hit10_pct": float((g["ret_10"] > 0).mean() * 100.0),
        "mean_mae10_pct": float(g["mae10_pct"].mean()),
        "mean_mfe10_pct": float(g["mfe10_pct"].mean()),
    }
    for h in [4, 6, 20]:
        out[f"mean_excess{h}_pct"] = float(g[f"excess_{h}"].mean() * 100.0)
    return out


def binary_state_analysis(qf: pd.DataFrame, years: tuple[int, int]) -> dict:
    lo, hi = years
    d = qf[(qf["year"] >= lo) & (qf["year"] <= hi)].copy()
    out = {}
    for name in INDICATORS:
        col = f"{name}_bull"
        out[name] = {
            "bull": summarize_qf_group(d[d[col] == True]),
            "bear": summarize_qf_group(d[d[col] == False]),
        }
        if len(d[d[col] == True]) and len(d[d[col] == False]):
            out[name]["bull_minus_bear_excess10_pct_points"] = (
                out[name]["bull"]["mean_excess10_pct"] - out[name]["bear"]["mean_excess10_pct"]
            )
    return out


def tertile_analysis(qf: pd.DataFrame) -> dict:
    discovery = qf[(qf["year"] >= 2024) & (qf["year"] <= 2025)].copy()
    holdout = qf[qf["year"] == 2026].copy()
    allp = qf[qf["year"] >= 2024].copy()
    out = {}

    for name in INDICATORS:
        out[name] = {}
        for feat in FEATURES:
            col = f"{name}_{feat}"
            vals = discovery[col].dropna().astype(float)
            if len(vals) < 10:
                continue
            q1, q2 = np.quantile(vals, [1/3, 2/3])

            def classify(v):
                if not np.isfinite(v):
                    return None
                if v <= q1:
                    return "low"
                if v <= q2:
                    return "mid"
                return "high"

            item = {"discovery_cutpoints": [float(q1), float(q2)]}
            for label, frame in [
                ("discovery_2024_2025", discovery),
                ("holdout_2026", holdout),
                ("all_2024_2026", allp),
            ]:
                tmp = frame[[col, "excess_10", "ret_10", "mae10_pct", "mfe10_pct", "symbol"]].copy()
                tmp["bucket"] = tmp[col].apply(classify)
                item[label] = {
                    b: summarize_qf_group(
                        frame.loc[tmp.index[tmp["bucket"] == b]]
                    )
                    for b in ["low", "mid", "high"]
                }
                # Direction summary only; no winner threshold.
                low = item[label]["low"].get("mean_excess10_pct")
                high = item[label]["high"].get("mean_excess10_pct")
                item[label]["high_minus_low_excess10_pct_points"] = (
                    float(high - low) if high is not None and low is not None else None
                )
            out[name][feat] = item
    return out


def feature_correlations(qf: pd.DataFrame) -> dict:
    d = qf[(qf["year"] >= 2024) & (qf["year"] <= 2026)].copy()
    cols = [f"{name}_{feat}" for name in INDICATORS for feat in FEATURES]
    corr = d[cols].corr(method="spearman")
    out = {}
    # Compact same-feature cross-indicator correlations.
    for feat in FEATURES:
        sub = [f"{name}_{feat}" for name in INDICATORS]
        out[feat] = {}
        for i, a in enumerate(sub):
            for b in sub[i + 1:]:
                v = corr.loc[a, b]
                out[feat][f"{a.split('_')[0]}__{b.split('_')[0]}"] = float(v) if np.isfinite(v) else None
    return out


def top_event_removal(qf: pd.DataFrame) -> dict:
    d = qf[qf["year"] >= 2024].copy().sort_values("excess_10", ascending=False)
    out = {}
    for k in [1, 3, 5, 10, 20]:
        y = d.iloc[k:] if len(d) > k else d.iloc[0:0]
        out[str(k)] = {
            "n": int(len(y)),
            "mean_excess10_pct": float(y["excess_10"].mean() * 100.0) if len(y) else None,
        }
    return out


def main() -> None:
    spy_i = regular_1h(fetch_symbol("SPY", "1h", "729d"))
    spy_h4 = resample_closed_4h(spy_i, "SPY")

    frames: dict[str, pd.DataFrame] = {}
    for k, sym in enumerate(SYMBOLS, 1):
        print(f"[{k}/{len(SYMBOLS)}] {sym}")
        df = prepare_symbol(sym, spy_h4)
        if df is not None:
            frames[sym] = add_probes(df)
    print("frames", len(frames))

    # Study A.
    study_a = {}
    all_events = []
    all_random_summaries = []
    for name in INDICATORS:
        rows = []
        col = f"{name}_cross_up"
        for sym, df in frames.items():
            for i in np.flatnonzero(df[col].fillna(False).to_numpy()):
                if i < WARMUP:
                    continue
                rec = forward_record(sym, df, spy_h4, int(i), f"{name}_cross_up")
                if rec is not None:
                    rec["indicator"] = name
                    rows.append(rec)
        events = pd.DataFrame(rows)
        if not events.empty:
            all_events.append(events)
        comp, rdf = random_compare(events, frames, spy_h4, name)
        rdf["indicator"] = name
        all_random_summaries.append(rdf)

        yearly = {}
        for y, g in events.groupby("year"):
            yearly[str(int(y))] = summarize_forward(g)

        sym10 = []
        for sym, g in events.groupby("symbol"):
            v = g["excess_10"].dropna().astype(float)
            if len(v):
                sym10.append({
                    "symbol": sym, "n": int(len(v)),
                    "mean_excess10_pct": float(v.mean() * 100.0),
                })
        sym10 = sorted(sym10, key=lambda z: z["mean_excess10_pct"], reverse=True)

        study_a[name] = {
            "summary": summarize_forward(events),
            "matched_random": comp,
            "yearly": yearly,
            "symbol_concentration_10bar": sym10,
        }

    if all_events:
        pd.concat(all_events, ignore_index=True).to_csv(OUT / "standalone_cross_events.csv", index=False)
    if all_random_summaries:
        pd.concat(all_random_summaries, ignore_index=True).to_csv(OUT / "random_matched_summaries.csv", index=False)

    # Study B.
    qf_rows = []
    for sym, df in frames.items():
        for i in np.flatnonzero(df["qf_event"].fillna(False).to_numpy()):
            if i < WARMUP:
                continue
            rec = qf_record(sym, df, spy_h4, int(i))
            if rec is not None:
                qf_rows.append(rec)
    qf = pd.DataFrame(qf_rows)
    qf.to_csv(OUT / "qf_probe_features.csv", index=False)

    study_b = {
        "qf_n": int(len(qf)),
        "binary_state_discovery_2024_2025": binary_state_analysis(qf, (2024, 2025)),
        "binary_state_holdout_2026": binary_state_analysis(qf, (2026, 2026)),
        "tertiles": tertile_analysis(qf),
        "feature_correlations_spearman": feature_correlations(qf),
        "top_event_removal": top_event_removal(qf),
    }

    payload = {
        "data_note": "30-symbol DST-safe 4H surrogate; 2024-2025 discovery, 2026 holdout; not canonical 131-symbol PIT",
        "definitions": {
            "EMA": "EMA20/EMA40",
            "HEMA": "existing HEMA20/HEMA40",
            "HMA": "Hull MA 20/40: WMA(2*WMA(n/2)-WMA(n),sqrt(n))",
            "KAMA": "Kaufman adaptive MA 20/40, fast=2 slow=30",
            "ZLEMA": "zero-lag EMA 20/40 with lag=floor((n-1)/2)",
        },
        "study_a": study_a,
        "study_b": study_b,
    }
    (OUT / "results.json").write_text(json.dumps(payload, indent=2))
    print("TREND_PROBE_START")
    print(json.dumps(payload, indent=2))
    print("TREND_PROBE_END")


if __name__ == "__main__":
    main()
