#!/usr/bin/env python3
"""CONSERVATIVE execution replay of the 237-trade baseline (research audit).

Replays the EXACT baseline trade list generated by pine_backtest.gen_pine_trades
(imported UNMODIFIED) under a conservative fill model:

  MODELED (baseline, pine_backtest.py):
    - entry at next-bar open, exact price, 0 slippage
    - NO intrabar stop: exits only when bar CLOSE < runner -> next-bar open
    - TP1: 50% at exact limit price when bar high >= TP1
    - EMA55/trend exits: close-evaluated -> next-bar open, exact price
    - gaps through the stop: filled at the next OPEN (realistic direction),
      but only AFTER the close triggered; intrabar gap-through-stop never seen
    - no Profit Protect, no 30-bar timeout, no stop-wins-ties logic
    - costs: 25bps subtracted once per trade (blended)

  CONSERVATIVE (this script):
    - entry: next-bar open + 5bps adverse (buy)
    - resting stop-market at the stop level: intrabar check on every bar,
      stop wins same-bar ties vs TP1
    - gap through stop (bar open <= stop): fill AT THE OPEN (adverse),
      minus 10bps adverse slippage on the fill
    - intrabar stop touch: fill at stop price minus 10bps adverse slippage
    - TP1: unchanged detection (bar high >= TP1), 50% at exact limit price
      (a real limit fills at the limit or better; ignoring gap-up improvement
      is conservative)
    - EMA55/trend exits: close-evaluated -> next-bar open minus 5bps adverse
    - R denominated in the PLANNED risk unit (baseline risk_frac) so the
      expectancy gap is pure execution, not re-denominated risk
    - costs: identical 25bps once per trade (same convention as baseline)

Slippage justification:
    5bps on market/open fills ~ 2-3x the typical 1-3bps effective spread of
    these liquid large caps; small vs the ~4% average planned risk width.
    10bps on stop-market fills: stop orders trigger into adverse momentum when
    spreads widen; 10bps adverse is a conservative upper bound for liquid names
    at research size, still << the 1.5*ATR stop distance (~3-6% of price).

NOT changed here (documented divergences, reported as diagnostics only):
    Profit Protect and the 30-bar timeout are Mode B (v54_exit_tracker.py)
    features absent from the backtester. They are NOT added to the replay
    (that would conflate execution realism with rule changes). Diagnostics
    below measure how often they would have bound.

Research only. Nothing frozen touched. Output: JSON + printed summary.
"""
import json
import os
import sys

import numpy as np
import pandas as pd

BASE = "/home/hatch/workspace/quality-flow-scanner-v5"
OUTDIR = os.path.join(BASE, "research_audit", "execution")
os.makedirs(OUTDIR, exist_ok=True)
CACHE = os.path.join(BASE, "pine_entry_timing_backtest", "cache")
sys.path.insert(0, BASE)
import pine_backtest as pb  # noqa: E402  (UNMODIFIED)

WATCHLIST = ["QQQ", "SMCI", "PLTR", "ANET", "SOFI", "RKLB",
             "ONDS", "DRAM", "SPCX", "ASTX", "BBAI", "NIO", "HOOD", "AMD"]

SLIP_ENTRY = 0.0005   # 5bps adverse on entry at open
SLIP_MKT = 0.0005     # 5bps adverse on next-open market exits
SLIP_STOP = 0.0010    # 10bps adverse on stop-market fills
COST = 0.0025         # 25bps, same convention as baseline headline
TP_ATR, TRAIL_ATR = 2.0, 2.5


def load(sym):
    df = pd.read_pickle(os.path.join(CACHE, f"h4_{sym}.pkl"))
    return pb.add_pine_indicators(df)


def replay(tr, df):
    """Conservative replay of one baseline trade. Returns dict of results."""
    n = len(df)
    entry, stop0 = tr["entry"], tr["stop"]
    risk_frac = (entry - stop0) / entry  # planned risk unit
    entry_idx = int(df.index.searchsorted(tr["entry_time"]))
    atr_sig = float(df["atr"].iloc[entry_idx - 1])
    tp1 = entry + atr_sig * TP_ATR

    entry_c = entry * (1 + SLIP_ENTRY)
    runner = stop0
    tp_hit = False
    r1 = None
    fill = None
    reason = None
    exit_idx = n - 1
    stop_events = {"gap_through": False, "intrabar_catch": False}

    for i in range(entry_idx, n):
        b = df.iloc[i]
        o, h, l, c = (float(b["Open"]), float(b["High"]),
                      float(b["Low"]), float(b["Close"]))
        # --- intrabar resting stop (stop wins ties) ---
        if l <= runner:
            if o <= runner:
                stop_events["gap_through"] = True
                fill = o * (1 - SLIP_STOP)
            else:
                fill = runner * (1 - SLIP_STOP)
            stop_events["intrabar_catch"] = True
            reason = "runner-stop" if tp_hit else "stop"
            exit_idx = i
            break
        # --- TP1 limit ---
        if not tp_hit and h >= tp1:
            tp_hit = True
            r1 = (tp1 - entry_c) / entry_c / risk_frac
        # --- trail ratchet at close (Pine truth) ---
        if tp_hit:
            runner = max(runner, c - float(b["atr"]) * TRAIL_ATR)
        # --- close-evaluated exits -> next bar open ---
        trend_bear = b["e21"] < b["e55"] and c < b["e200"]
        if c < b["e55"] or trend_bear:
            reason = "ema55-bear" if trend_bear else "ema55-break"
            fill = (float(df["Open"].iloc[i + 1]) if i + 1 < n else c) * (1 - SLIP_MKT)
            exit_idx = i + 1 if i + 1 < n else i
            break
    if fill is None:  # never triggered: exit at last close
        fill = float(df["Close"].iloc[-1]) * (1 - SLIP_MKT)
        reason = "end-of-data"
        exit_idx = n - 1

    r2 = (fill - entry_c) / entry_c / risk_frac
    gross = (0.5 * r1 + 0.5 * r2) if r1 is not None else r2
    net_r = gross - COST / risk_frac
    return {
        "symbol": tr["symbol"], "net_r_cons": net_r, "gross_r_cons": gross,
        "tp1_hit": tp_hit, "reason_cons": reason,
        "hold_bars_cons": exit_idx - entry_idx,
        "gap_through_stop": stop_events["gap_through"],
        "intrabar_stop_catch": stop_events["intrabar_catch"],
        "tp1_level": tp1, "entry_cons": entry_c,
    }


def main():
    data = {s: load(s) for s in WATCHLIST}
    trades = []
    for s in WATCHLIST:
        ts, _ = pb.gen_pine_trades(s, data[s])
        trades.extend(ts)
    trades.sort(key=lambda t: t["entry_time"])
    assert len(trades) == 237, f"expected 237 baseline trades, got {len(trades)}"

    rows, rep = [], []
    for tr in trades:
        base_r = pb._outcome(tr["entry"], tr["stop"], tr["exit"], COST)[2]
        c = replay(tr, data[tr["symbol"]])
        c["net_r_base"] = base_r
        c["delta_r"] = c["net_r_cons"] - base_r
        c["hold_bars_base"] = tr["hold_bars"]
        c["reason_base"] = tr["reason"]
        rows.append(c)
        rep.append(c)

    R = pd.DataFrame(rows)
    base_mean = R["net_r_base"].mean()
    cons_mean = R["net_r_cons"].mean()
    gap = cons_mean - base_mean

    # --- diagnostics ---
    caught = R[R["intrabar_stop_catch"]]
    gaps = R[R["gap_through_stop"]]
    long_holds = (R["hold_bars_base"] > 30).sum()
    long_r = R.loc[R["hold_bars_base"] > 30, "net_r_base"].sum()
    reason_chg = (R["reason_cons"] != R["reason_base"]).sum()
    tp1_base_rate = np.mean([t["tp1_hit"] for t in trades])
    tp1_cons_rate = R["tp1_hit"].mean()

    out = {
        "n": len(R),
        "baseline_exp_25bps": round(float(base_mean), 4),
        "conservative_exp_25bps": round(float(cons_mean), 4),
        "execution_gap_R": round(float(gap), 4),
        "execution_gap_pct_of_baseline": round(float(gap / base_mean) * 100, 1) if base_mean else None,
        "win_rate_base_pct": round(float((R['net_r_base'] > 0).mean()) * 100, 1),
        "win_rate_cons_pct": round(float((R['net_r_cons'] > 0).mean()) * 100, 1),
        "intrabar_stop_catches": int(caught.shape[0]),
        "gap_through_stop_fills": int(gaps.shape[0]),
        "avg_delta_when_caught_R": round(float(caught["delta_r"].mean()), 4) if len(caught) else None,
        "trades_with_changed_reason": int(reason_chg),
        "tp1_hit_rate_base": round(float(tp1_base_rate), 3),
        "tp1_hit_rate_cons": round(float(tp1_cons_rate), 3),
        "avg_hold_bars_base": round(float(R["hold_bars_base"].mean()), 1),
        "avg_hold_bars_cons": round(float(R["hold_bars_cons"].mean()), 1),
        "trades_held_gt30bars": int(long_holds),
        "total_R_of_gt30bar_trades_base": round(float(long_r), 2),
        "slippage_assumptions_bps": {"entry": 5, "market_exit": 5, "stop": 10},
        "cost_bps": 25,
        "per_trade": rep,
    }
    with open(os.path.join(OUTDIR, "conservative_replay_results.json"), "w") as f:
        json.dump(out, f, indent=1, default=str)

    print(f"baseline expectancy (25bps):      {base_mean:+.4f}R")
    print(f"conservative expectancy (25bps):  {cons_mean:+.4f}R")
    print(f"EXECUTION GAP:                    {gap:+.4f}R "
          f"({gap/base_mean*100:+.1f}% of baseline)")
    print(f"win rate: {out['win_rate_base_pct']}% -> {out['win_rate_cons_pct']}%")
    print(f"intrabar stop catches (close missed, stop hit): {len(caught)}/{len(R)}")
    print(f"gap-through-stop fills honored at open:         {len(gaps)}/{len(R)}")
    print(f"avg delta on caught trades: {out['avg_delta_when_caught_R']}R")
    print(f"TP1 hit rate: {tp1_base_rate:.1%} -> {tp1_cons_rate:.1%}")
    print(f"avg hold bars: {out['avg_hold_bars_base']} -> {out['avg_hold_bars_cons']}")
    print(f"trades held >30 bars (Mode B timeout absent): {long_holds}, "
          f"their total R: {long_r:+.2f}R")


if __name__ == "__main__":
    main()
